# Generated by Django 5.2.4 on 2025-08-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_alter_comment_options_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_post',
            new_name='parent_comment',
        ),
    ]
